---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ambassador
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /ambassador/v0/check_ready
    port: 30887