---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ambassador
spec:
  releaseName: ambassador
  chart:
    repository: https://getambassador.io
    name: ambassador
    version: 6.5.10
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/dubuc/ambassador-flux/helm/base/ambassador/values.yaml
      optional: true